"""add refined_context to render_jobs

Revision ID: 7c3881a3c229
Revises: 9cc01f19d7d2
Create Date: 2026-04-18 13:33:45.006903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3881a3c229'
down_revision: Union[str, Sequence[str], None] = '9cc01f19d7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('render_jobs', sa.Column('refined_context', sa.Text(), nullable=True), schema='factory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('render_jobs', 'refined_context', schema='factory')
    # ### end Alembic commands ###
