"""initial_schema

Revision ID: 93493ebb621c
Revises: 
Create Date: 2026-04-10 08:22:47.419386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '93493ebb621c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create schema and extension
    op.execute('CREATE SCHEMA IF NOT EXISTS factory')
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('render_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('pre_context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RESEARCHING', 'FACT_CHECKING_RESEARCH', 'SCRIPTING', 'FACT_CHECKING_SCRIPT', 'ASSET_GENERATION', 'COMPLETED', 'FAILED', 'HUMAN_REVIEW_NEEDED', name='job_status', schema='factory'), server_default='PENDING', nullable=False),
    sa.Column('strict_compliance_mode', sa.Boolean(), nullable=False),
    sa.Column('final_video_url', sa.String(), nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='factory'
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', postgresql.ENUM('VISUAL_VEO', 'AUDIO_LYRIA', 'VOICEOVER', 'SUBTITLE_JSON', 'DATA_CHART', name='asset_type', schema='factory'), nullable=False),
    sa.Column('url_or_path', sa.String(), nullable=False),
    sa.Column('render_meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['factory.render_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='factory'
    )
    op.create_table('research_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['factory.render_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='factory'
    )
    op.create_index('ix_research_meta_gin', 'research_chunks', ['meta'], unique=False, schema='factory', postgresql_using='gin')
    op.create_table('scripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('feedback_history', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['factory.render_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='factory'
    )
    op.create_table('fact_check_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('claim_text', sa.String(), nullable=False),
    sa.Column('verdict', postgresql.ENUM('SUPPORTED', 'CONTESTED', 'UNSUPPORTED', 'UNCERTAIN', name='verdict_status', schema='factory'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_references', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='check_confidence_range'),
    sa.ForeignKeyConstraint(['script_id'], ['factory.scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='factory'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_check_claims', schema='factory')
    op.drop_table('scripts', schema='factory')
    op.drop_index('ix_research_meta_gin', table_name='research_chunks', schema='factory', postgresql_using='gin')
    op.drop_table('research_chunks', schema='factory')
    op.drop_table('assets', schema='factory')
    op.drop_table('render_jobs', schema='factory')
    # ### end Alembic commands ###
