"""add_missing_indices

Revision ID: d5e094723ec6
Revises: 9d4cd07a11b1
Create Date: 2026-04-13 04:05:54.736411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5e094723ec6"
down_revision: Union[str, Sequence[str], None] = "9d4cd07a11b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_assets_job_type",
        "assets",
        ["job_id", "asset_type"],
        unique=False,
        schema="factory",
    )
    op.create_index(
        op.f("ix_factory_assets_job_id"),
        "assets",
        ["job_id"],
        unique=False,
        schema="factory",
    )
    op.create_index(
        op.f("ix_factory_fact_check_claims_script_id"),
        "fact_check_claims",
        ["script_id"],
        unique=False,
        schema="factory",
    )
    op.create_index(
        "ix_render_jobs_active_queue",
        "render_jobs",
        ["status"],
        unique=False,
        schema="factory",
        postgresql_where=sa.text("status NOT IN ('COMPLETED', 'FAILED')"),
    )
    op.create_index(
        op.f("ix_factory_research_chunks_job_id"),
        "research_chunks",
        ["job_id"],
        unique=False,
        schema="factory",
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_research_embedding_hnsw
        ON factory.research_chunks USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        """
    )
    op.create_index(
        op.f("ix_factory_scripts_job_id"),
        "scripts",
        ["job_id"],
        unique=False,
        schema="factory",
    )
    op.create_unique_constraint(
        "uq_script_job_version", "scripts", ["job_id", "version"], schema="factory"
    )
    op.execute("""
    CREATE OR REPLACE FUNCTION factory.update_modified_column()
    RETURNS TRIGGER AS $$
    BEGIN
        NEW.updated_at = now();
        RETURN NEW;
    END;
    $$ language 'plpgsql';
    """)

    op.execute("""
    CREATE TRIGGER update_render_jobs_modtime
        BEFORE UPDATE ON factory.render_jobs
        FOR EACH ROW EXECUTE PROCEDURE factory.update_modified_column();
    """)
    op.execute("""
    CREATE TRIGGER update_scripts_modtime
        BEFORE UPDATE ON factory.scripts
        FOR EACH ROW EXECUTE PROCEDURE factory.update_modified_column();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_script_job_version", "scripts", schema="factory", type_="unique"
    )
    op.drop_index(
        op.f("ix_factory_scripts_job_id"), table_name="scripts", schema="factory"
    )
    op.drop_index(
        "ix_research_embedding_hnsw",
        table_name="research_chunks",
        schema="factory",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(
        op.f("ix_factory_research_chunks_job_id"),
        table_name="research_chunks",
        schema="factory",
    )
    op.drop_index(
        "ix_render_jobs_active_queue",
        table_name="render_jobs",
        schema="factory",
        postgresql_where=sa.text("status NOT IN ('COMPLETED', 'FAILED')"),
    )
    op.drop_index(
        op.f("ix_factory_fact_check_claims_script_id"),
        table_name="fact_check_claims",
        schema="factory",
    )
    op.drop_index(
        op.f("ix_factory_assets_job_id"), table_name="assets", schema="factory"
    )
    op.drop_index("ix_assets_job_type", table_name="assets", schema="factory")

    op.execute("DROP FUNCTION IF EXISTS factory.update_modified_column() CASCADE;")
    # ### end Alembic commands ###
