/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs__get"];
        put?: never;
        /** Create Render Job */
        post: operations["create_render_job_api_v1_jobs__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Render Job */
        get: operations["get_render_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/approve-script": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Script */
        post: operations["approve_script_api_v1_jobs__job_id__approve_script_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetRenderMeta
         * @description Schema for the JSONB render_meta column in Assets.
         */
        AssetRenderMeta: {
            /** Start Time Sec */
            start_time_sec?: number | null;
            /** End Time Sec */
            end_time_sec?: number | null;
            /**
             * Synthid Watermark
             * @description Google SynthID signature for compliance
             */
            synthid_watermark?: string | null;
            /**
             * Prompt Used
             * @description The exact Veo/Lyria prompt used
             */
            prompt_used?: string | null;
        };
        /**
         * AssetResponse
         * @description Outputs for Step 7: Multi-modal generated assets.
         */
        AssetResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            asset_type: components["schemas"]["AssetTypeEnum"];
            /** Url Or Path */
            url_or_path: string;
            render_meta: components["schemas"]["AssetRenderMeta"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AssetTypeEnum
         * @enum {string}
         */
        AssetTypeEnum: "VISUAL_VEO" | "AUDIO_LYRIA" | "VOICEOVER" | "SUBTITLE_JSON" | "DATA_CHART";
        /** BlogFormatPayload */
        BlogFormatPayload: {
            /**
             * Format
             * @default blog
             * @constant
             */
            _format: "blog";
            /**
             * Version
             * @default 1
             */
            _version: number;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string;
            /** Sections */
            sections: components["schemas"]["BlogSection"][];
            seo_meta: components["schemas"]["SeoMeta"];
            /** Tags */
            tags: string[];
            /** Call To Action */
            call_to_action: string;
        };
        /** BlogSection */
        BlogSection: {
            /** Heading */
            heading: string;
            /** Body */
            body: string;
            /** Key Takeaway */
            key_takeaway: string;
            /** Sources Used */
            sources_used?: string[];
            /** Word Count */
            word_count: number;
        };
        /** CarouselFormatPayload */
        CarouselFormatPayload: {
            /**
             * Format
             * @default carousel
             * @constant
             */
            _format: "carousel";
            /**
             * Version
             * @default 1
             */
            _version: number;
            /** Slides */
            slides: components["schemas"]["CarouselSlide"][];
            /** Thread Title */
            thread_title: string;
            /** Hashtags */
            hashtags: string[];
            /** Cta Slide */
            cta_slide: string;
            /** Char Limit Violations */
            char_limit_violations?: string[];
        };
        /** CarouselSlide */
        CarouselSlide: {
            /** Slide Number */
            slide_number: number;
            /** Text */
            text: string;
            /** Visual Prompt */
            visual_prompt: string;
            /** Hook Type */
            hook_type: string;
            /** Sources Used */
            sources_used?: string[];
        };
        /**
         * FactCheckClaimResponse
         * @description Outputs for Step 4 & 6: Red Team Evaluation Results.
         */
        FactCheckClaimResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Claim Text */
            claim_text: string;
            verdict: components["schemas"]["VerdictEnum"];
            /** Confidence */
            confidence: number;
            /**
             * Evidence Text
             * @description Evidence text supporting this verdict
             */
            evidence_text?: string | null;
            /**
             * Evidence References
             * @description IDs of ResearchChunks
             */
            evidence_references?: string[];
        };
        /**
         * FormatTypeEnum
         * @enum {string}
         */
        FormatTypeEnum: "all" | "video" | "blog" | "carousel";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobCreateRequest
         * @description Payload for Step 1: User inserts topic & context.
         */
        JobCreateRequest: {
            /**
             * Topic
             * @example BRICS De-dollarization 2025
             */
            topic: string;
            pre_context: components["schemas"]["PreContextPayload"];
            /**
             * Strict Compliance Mode
             * @description Enforce rigorous fact-checking
             * @default true
             */
            strict_compliance_mode: boolean;
            /**
             * @description Output format: all, video, blog, or carousel
             * @default all
             */
            format_type: components["schemas"]["FormatTypeEnum"];
            /** @description Target platform: twitter, linkedin, instagram, youtube */
            platform?: components["schemas"]["PlatformEnum"] | null;
        };
        /**
         * JobStatusEnum
         * @enum {string}
         */
        JobStatusEnum: "PENDING" | "RESEARCHING" | "FACT_CHECKING_RESEARCH" | "SCRIPTING" | "FACT_CHECKING_SCRIPT" | "FORMATTING" | "ASSET_GENERATION" | "COMPLETED" | "FAILED" | "HUMAN_REVIEW_NEEDED";
        /**
         * PlatformEnum
         * @enum {string}
         */
        PlatformEnum: "twitter" | "linkedin" | "instagram" | "youtube";
        /**
         * PreContextPayload
         * @description Schema for the JSONB pre_context column provided by the user.
         */
        PreContextPayload: {
            /**
             * Source Urls
             * @description URLs to scrape for research
             */
            source_urls?: string[];
            /**
             * Raw Text
             * @description Raw copied text or book excerpts
             */
            raw_text?: string | null;
            /**
             * Target Audience
             * @description e.g., Academics, TikTok, Investors
             * @default General
             */
            target_audience: string;
            /**
             * Guardrail Strictness
             * @description Defines how aggressively the Red Team operates
             * @default High
             */
            guardrail_strictness: string;
        };
        /**
         * RenderJobResponse
         * @description Outputs for Step 8: The Master Object State.
         */
        RenderJobResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Topic */
            topic: string;
            status: components["schemas"]["JobStatusEnum"];
            /** Strict Compliance Mode */
            strict_compliance_mode: boolean;
            /** @default all */
            format_type: components["schemas"]["FormatTypeEnum"] | null;
            platform?: components["schemas"]["PlatformEnum"] | null;
            /** Final Video Url */
            final_video_url: string | null;
            /** Refined Context */
            refined_context?: string | null;
            /** Error Log */
            error_log: {
                [key: string]: unknown;
            } | null;
            /**
             * Pre Context
             * @description Original user-provided context
             */
            pre_context?: {
                [key: string]: unknown;
            } | null;
            /** Scripts */
            scripts?: components["schemas"]["ScriptResponse"][];
            /** Assets */
            assets?: components["schemas"]["AssetResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ScriptApprovalRequest
         * @description Payload for Human-in-the-loop overrides.
         */
        ScriptApprovalRequest: {
            /**
             * Is Approved
             * @description Approve or reject the script
             */
            is_approved: boolean;
            /**
             * Human Feedback
             * @description Feedback to send back to the Script Agent
             */
            human_feedback?: string | null;
        };
        /**
         * ScriptResponse
         * @description Outputs for Step 5: The Agentic Script.
         */
        ScriptResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Role
             * @default master
             */
            role: string;
            /** Version */
            version: number;
            /** Content */
            content: string;
            /** Is Approved */
            is_approved: boolean;
            /** Feedback History */
            feedback_history: (string | {
                [key: string]: unknown;
            })[];
            /** Claims */
            claims?: components["schemas"]["FactCheckClaimResponse"][];
            /** Format Type */
            format_type?: string | null;
            /** Format Payload */
            format_payload?: (components["schemas"]["VideoFormatPayload"] | components["schemas"]["BlogFormatPayload"] | components["schemas"]["CarouselFormatPayload"]) | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SeoMeta */
        SeoMeta: {
            /** Meta Title */
            meta_title: string;
            /** Meta Description */
            meta_description: string;
            /** Keywords */
            keywords: string[];
            /** Canonical Url */
            canonical_url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerdictEnum
         * @enum {string}
         */
        VerdictEnum: "SUPPORTED" | "CONTESTED" | "UNSUPPORTED" | "UNCERTAIN";
        /** VideoFormatPayload */
        VideoFormatPayload: {
            /**
             * Format
             * @default video
             * @constant
             */
            _format: "video";
            /**
             * Version
             * @default 1
             */
            _version: number;
            /** Scenes */
            scenes: components["schemas"]["VideoScene"][];
            /** Total Duration Seconds */
            total_duration_seconds: number;
            /** Visual Style */
            visual_style: string;
            /**
             * Audio Direction
             * @default
             */
            audio_direction: string;
        };
        /** VideoScene */
        VideoScene: {
            /** Scene Number */
            scene_number: number;
            /** Narration Text */
            narration_text: string;
            /** Visual Prompt */
            visual_prompt: string;
            /**
             * Audio Cue
             * @default
             */
            audio_cue: string;
            /** Duration Seconds */
            duration_seconds: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_jobs_api_v1_jobs__get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatusEnum"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderJobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_render_job_api_v1_jobs__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_render_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_script_api_v1_jobs__job_id__approve_script_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
