"""add_device_id_column

Revision ID: 22520681da2b
Revises: 25b1c3d4e5f6
Create Date: 2026-05-23 08:11:05.064174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22520681da2b'
down_revision: Union[str, Sequence[str], None] = '25b1c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('render_jobs', sa.Column('device_id', sa.String(), nullable=True), schema='factory')
    op.alter_column('render_jobs', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='factory')
    op.drop_index(op.f('ix_render_jobs_locked_at'), table_name='render_jobs', schema='factory', postgresql_where='(locked_at IS NOT NULL)')
    op.drop_index(op.f('ix_research_embedding_hnsw'), table_name='research_chunks', schema='factory', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index('ix_research_embedding_hnsw', 'research_chunks', ['embedding'], unique=False, schema='factory', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_research_embedding_hnsw', table_name='research_chunks', schema='factory', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_research_embedding_hnsw'), 'research_chunks', ['embedding'], unique=False, schema='factory', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_render_jobs_locked_at'), 'render_jobs', ['locked_at'], unique=False, schema='factory', postgresql_where='(locked_at IS NOT NULL)')
    op.alter_column('render_jobs', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='factory')
    op.drop_column('render_jobs', 'device_id', schema='factory')
    # ### end Alembic commands ###
