"""pre_context to explicit columns

Revision ID: 2695ce2f5280
Revises: 22520681da2b
Create Date: 2026-05-25 08:21:00.187257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2695ce2f5280"
down_revision: Union[str, Sequence[str], None] = "22520681da2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "render_jobs", sa.Column("title", sa.String(), nullable=False), schema="factory"
    )
    op.add_column(
        "render_jobs",
        sa.Column("user_reference", sa.Text(), server_default="", nullable=False),
        schema="factory",
    )
    op.add_column(
        "render_jobs",
        sa.Column(
            "source_urls",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        schema="factory",
    )
    op.add_column(
        "render_jobs",
        sa.Column(
            "story_directives",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        schema="factory",
    )
    op.drop_column("render_jobs", "topic", schema="factory")
    op.drop_column("render_jobs", "citation_index", schema="factory")
    op.drop_column("render_jobs", "pre_context", schema="factory")
    op.drop_column("render_jobs", "research_confidence", schema="factory")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "render_jobs",
        sa.Column(
            "research_confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema="factory",
    )
    op.add_column(
        "render_jobs",
        sa.Column(
            "pre_context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        schema="factory",
    )
    op.add_column(
        "render_jobs",
        sa.Column(
            "citation_index",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        schema="factory",
    )
    op.add_column(
        "render_jobs",
        sa.Column("topic", sa.VARCHAR(), autoincrement=False, nullable=False),
        schema="factory",
    )
    op.drop_column("render_jobs", "story_directives", schema="factory")
    op.drop_column("render_jobs", "source_urls", schema="factory")
    op.drop_column("render_jobs", "user_reference", schema="factory")
    op.drop_column("render_jobs", "title", schema="factory")
    # ### end Alembic commands ###
