"""add_global_scope

Revision ID: 2796db25c720
Revises: c1d2e3f4a5b6
Create Date: 2026-05-30 04:47:35.059313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2796db25c720"
down_revision: Union[str, Sequence[str], None] = "c1d2e3f4a5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "research_chunks",
        "job_id",
        existing_type=sa.UUID(),
        nullable=True,
        schema="factory",
    )
    op.create_index(
        "ix_research_chunks_global",
        "research_chunks",
        ["id"],
        unique=False,
        schema="factory",
        postgresql_where=sa.text("meta->>'scope' = 'GLOBAL'"),
    )
    op.drop_constraint(
        op.f("research_chunks_job_id_fkey"),
        "research_chunks",
        schema="factory",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "research_chunks",
        "render_jobs",
        ["job_id"],
        ["id"],
        source_schema="factory",
        referent_schema="factory",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "research_chunks", schema="factory", type_="foreignkey")
    op.create_foreign_key(
        op.f("research_chunks_job_id_fkey"),
        "research_chunks",
        "render_jobs",
        ["job_id"],
        ["id"],
        source_schema="factory",
        referent_schema="factory",
        ondelete="CASCADE",
    )
    op.drop_index(
        "ix_research_chunks_global",
        table_name="research_chunks",
        schema="factory",
        postgresql_where=sa.text("meta->>'scope' = 'GLOBAL'"),
    )
    op.alter_column(
        "research_chunks",
        "job_id",
        existing_type=sa.UUID(),
        nullable=False,
        schema="factory",
    )
    # ### end Alembic commands ###
