"""add_triggers_and_refinements

Revision ID: 3c01721362c7
Revises: 93493ebb621c
Create Date: 2026-04-10 13:48:31.369985

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3c01721362c7"
down_revision: Union[str, Sequence[str], None] = "93493ebb621c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE OR REPLACE FUNCTION factory.update_modified_column()
    RETURNS TRIGGER AS $$
    BEGIN
        NEW.updated_at = now();
        RETURN NEW;
    END;
    $$ language 'plpgsql';
    """)

    op.execute("""
    CREATE TRIGGER update_render_jobs_modtime
        BEFORE UPDATE ON factory.render_jobs
        FOR EACH ROW EXECUTE PROCEDURE factory.update_modified_column();
    """)

    op.execute("""
    CREATE TRIGGER update_scripts_modtime
        BEFORE UPDATE ON factory.scripts
        FOR EACH ROW EXECUTE PROCEDURE factory.update_modified_column();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS update_scripts_modtime ON factory.scripts;")
    op.execute(
        "DROP TRIGGER IF EXISTS update_render_jobs_modtime ON factory.render_jobs;"
    )
    op.execute("DROP FUNCTION IF EXISTS factory.update_modified_column();")
    # ### end Alembic commands ###
