"""add_locked_columns_to_render_jobs

Revision ID: 9cc01f19d7d2
Revises: d5e094723ec6
Create Date: 2026-04-15 11:44:13.183605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9cc01f19d7d2"
down_revision: Union[str, Sequence[str], None] = "d5e094723ec6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "render_jobs",
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        schema="factory",
    )
    op.add_column(
        "render_jobs",
        sa.Column("locked_by", sa.String(length=36), nullable=True),
        schema="factory",
    )
    op.create_index(
        "ix_render_jobs_locked_at",
        "render_jobs",
        ["locked_at"],
        unique=False,
        schema="factory",
        postgresql_where=sa.text("locked_at IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_render_jobs_locked_at", table_name="render_jobs", schema="factory"
    )
    op.drop_column("render_jobs", "locked_by", schema="factory")
    op.drop_column("render_jobs", "locked_at", schema="factory")
    # ### end Alembic commands ###
