"""init_content_factory

Revision ID: 9d4cd07a11b1
Revises: bf0566ee2b9e
Create Date: 2026-04-10 14:13:24.775670

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9d4cd07a11b1"
down_revision: Union[str, Sequence[str], None] = "bf0566ee2b9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
