"""make_format_jobs_source_job_id_nullable

Revision ID: a4388489c303
Revises: 2797db25c721
Create Date: 2026-06-02 10:51:56.672122

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a4388489c303"
down_revision: Union[str, Sequence[str], None] = "2797db25c721"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "format_jobs",
        "source_job_id",
        existing_type=sa.UUID(),
        nullable=True,
        schema="factory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "format_jobs",
        "source_job_id",
        existing_type=sa.UUID(),
        nullable=False,
        schema="factory",
    )
    # ### end Alembic commands ###
